# Generated by Django 6.1.1 on 2026-09-25 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizou', models.BooleanField()),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hidratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_ml', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dose', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoGlicemica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('horario', models.TimeField()),
                ('momento', models.CharField(choices=[('JEJUM', 'Jejum'), ('ANTES_REFEICAO', 'Antes da refeição'), ('APOS_REFEICAO', 'Após a refeição'), ('ANTES_DORMIR', 'Antes de dormir'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TOMOU', 'Tomou'), ('NAO_TOMOU', 'Não tomou'), ('ESQUECEU', 'Esqueceu'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('intensidade', models.CharField(blank=True, max_length=30)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qualidade', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='registrodiario',
            constraint=models.UniqueConstraint(fields=('paciente', 'data'), name='registro_diario_paciente_data_unico'),
        ),
        migrations.AddField(
            model_name='alimentacao',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacoes', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='atividadefisica',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='hidratacao',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hidratacao', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='medicamentopaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='medicaoglicemica',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glicemias', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='registromedicamento',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_uso', to='acompanhamentos.medicamentopaciente'),
        ),
        migrations.AddField(
            model_name='registromedicamento',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='sintoma',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='acompanhamentos.registrodiario'),
        ),
        migrations.AddField(
            model_name='sono',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sono', to='acompanhamentos.registrodiario'),
        ),
    ]
