# Generated by Django 6.1.1 on 2026-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0002_alimentacao_atividadefisica_hidratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadefisica',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CAMINHADA', 'Caminhada'), ('CORRIDA', 'Corrida'), ('CICLISMO', 'Ciclismo'), ('MUSCULACAO', 'Musculação'), ('NATACAO', 'Natação'), ('ESPORTE', 'Esporte'), ('DANCA', 'Dança'), ('ALONGAMENTO', 'Alongamento'), ('OUTRA', 'Outra')], max_length=20),
        ),
    ]
