# Generated by Django 6.1.1 on 2026-09-25 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0003_alter_atividadefisica_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentacao',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='alimentacao',
            name='refeicao',
        ),
        migrations.AlterField(
            model_name='alimentacao',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacao', to='acompanhamentos.registrodiario'),
        ),
    ]
