# Generated by Django 6.1.1 on 2026-09-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0004_remove_alimentacao_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hidratacao',
            name='quantidade_ml',
        ),
        migrations.AddField(
            model_name='hidratacao',
            name='lembrou_de_se_hidratar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
