# Generated by Django 6.1.1 on 2026-09-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0005_remove_hidratacao_quantidade_ml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sono',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='sono',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='sono',
            name='qualidade',
        ),
        migrations.AddField(
            model_name='sono',
            name='descricao',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
