# Generated by Django 6.1.1 on 2026-09-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0006_remove_sono_horas_remove_sono_observacao_and_more'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('GLICEMIA_JEJUM', 'Glicemia em jejum'), ('ATIVIDADE', 'Atividade física'), ('ALIMENTACAO', 'Alimentação'), ('HIDRATACAO', 'Hidratação'), ('SONO', 'Sono'), ('SINTOMAS', 'Sintomas'), ('MEDICAMENTOS', 'Medicamentos'), ('FINALIZADO', 'Finalizado')], max_length=30)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado')], default='EM_ANDAMENTO', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos_estado', to='pacientes.paciente')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='acompanhamentos.registrodiario')),
            ],
        ),
    ]
