# Generated by Django 6.1.1 on 2026-09-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('profissional', 'Profissional'), ('leitura', 'Somente leitura')], default='profissional', max_length=20),
        ),
    ]
