# Generated by Django 6.1.1 on 2026-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='deve_alterar_senha',
            field=models.BooleanField(default=False),
        ),
    ]
